
main_dir: "/Users/benbarry/Library/CloudStorage/Box-Box/endochill/Px_data"
raw_dir: "/Users/benbarry/Library/CloudStorage/Box-Box/endochill/Px_data/PxWHM022530/data/raw"
processed_dir: "/Users/benbarry/Library/CloudStorage/Box-Box/endochill/Px_data/PxWHM022530/data/processed"
figs_dir: "/Users/benbarry/Library/CloudStorage/Box-Box/endochill/Px_data/PxWHM022530/data/processed/figs"
stdcurve_dir: "/Users/benbarry/Library/CloudStorage/Box-Box/endochill/Px_data/PxWHM022530/data/processed/stdcurve"
plate_layout_path: "/Users/benbarry/Library/CloudStorage/Box-Box/endochill/protocols/PlateLayout_HM_version.xlsx"
std_concentrations:
  - 250.0
  - 125.0
  - 62.5
  - 31.25
  - 15.6
  - 7.8
  - 3.9
  - 0.0
diltution_factor: 15
#create a lookup table for pam and LPS
pam_lookup:
  - name: "Pam_1"
    conc: 0.0125
  - name: "Pam_2"
    conc: 0.025
  - name: "Pam_3"
    conc: 0.05
  - name: "Pam_4"
    conc: 0.1
  - name: "Pam_5"
    conc: 1.0
  - name: "Pam_6"
    conc: 5.0
  - name: "Pam_7"
    conc: 10.0
  - name: "Pam_8"
    conc: 50.0
  - name: "Pam_9"
    conc: 100.0
  - name: "Pam_10"
    conc: 500.0
  - name: "Pam_11"
    conc: 1000.0

LPS_lookup:
  - name: "LPS_1"
    conc: 0.0125
  - name: "LPS_2"
    conc: 0.025
  - name: "LPS_3"
    conc: 0.05
  - name: "LPS_4"
    conc: 0.1
  - name: "LPS_5"
    conc: 1.0
  - name: "LPS_6"
    conc: 10.0
  - name: "LPS_7"
    conc: 100.0
  - name: "LPS_8"
    conc: 1000.0
  - name: "LPS_9"
    conc: 5000.0
  - name: "LPS_10"
    conc: 10000.0

